// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInGVim
{
    static class Vsix
    {
        public const string Id = "a69e33af-f9d6-4fce-b3b8-5e973a040a2a";
        public const string Name = "Open in GVim";
        public const string Description = "Adds a menu command that lets you open any solution, project, folder and/or file in GVim.";
        public const string Language = "en-US";
        public const string Version = "0.10";
        public const string Author = "Brennan Fee";
        public const string Tags = "vim, gvim";
    }
}
