// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInNeovim
{
    static class Vsix
    {
        public const string Name = "Open in Neovim";
        public const string Description = "Adds a menu command that lets you open any solution, project, folder and/or file in Neovim.";
        public const string Language = "en-US";
        public const string Version = "0.23";
        public const string Author = "Hangjit Rai";
        public const string Tags = "vim, gvim, neovim, nvim, nvim-qt";
    }
}
